#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

$bot = new Phergie\Irc\Bot\React\Bot;

$bot->setConfig([
    'connections' => require __DIR__ . '/config/connections.php',
    'plugins' => require __DIR__ . '/config/plugins.php',
]);

$bot->run();
